version: '3.5'
services:
  lifto:
    image: kingspm/lifto:0.1
    restart: always
    environment: 
      FLASK_APP: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./resources:/resources