version: '3.5'
services:
  mongodb:
    image: "bitnami/mongodb:5.0"
    environment:
      MONGO_INITDB_DATABASE: flask_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/bitnami/mongodb
